### ISSUE TITLE
Extension done

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/connect-four-unit-tests-renestadler#2]
Dear Mr. Stropek!
As already mentioned in todays meeting,
@michaelhitzker and i have a JavaUI and the required WPF-UI
and would like to collect the extra point.
Yours,
René Stadler
Michael Hitzker

**Comment by rstropek** [comment]
Java OMG 🤯😲. Two extra points for you. Greetings, Rainer Stropek.
